### ISSUE TITLE
Memory leak while watching a video (with all QT based browser tried so far so I guess it's a QT issue or my own issue)

### ISSUE THREAD

**Issue by puppinoo** [Meli10/Rocket-Browser#5]
**Describe the bug**
While watching a video memory slowly but constantly descreases until it got exausted (with swap partition too)

**To Reproduce**
1. Go to paramountplus.com
2. Click on on of many available videos
3. Play it

**Expected behavior**
Memory remains constants because is freed

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.10
 - Browser this one.
 - Version latest

Thanks.

**Comment by Meli10** [comment]
I may have fixed the leak in the memory. This stems from the tabs not closing properly. Due to not closing properly, they were still consuming memory/cache. This fix should give you a better experience. 

I do however have a question in regard to the memory leaks. How long does it take for you to experience a failure in memory? Is it after an hour or less than an hour? I ask because I can also set up an automatic periodic cache clearing timer. That way you can continue surfing the web/watching videos and it shouldn't interrupt anything you're doing on the current page you're on.

The developer of the PyQt library didn't include much low-level concepts like dynamic cache management. So in turn, memory management is a bit restricted to what you can accomplish using the QtWebEngine.

**Comment by puppinoo** [comment]
Great news.
Im testing right now.
Started a test streaming at 18.29 and I had 1.17GB used from htop.
Now it's still going and htop says I have 1.88GB busy and it's 20.56.

**Comment by puppinoo** [comment]
Also, Im not sure memory leak could be related to tabs because when I test I just open one single tab and stram the video in it.
And I'm talking about not just your project but so many QT5 based browsers I tried. All have this issue.
But I hope you're right.

**Comment by Meli10** [comment]
Quick update:
I believe the underlying issue from all of this stems from using the PyQt5 library. When the developer introduced PyQt6, they apparently fixed this issue. I'm currently migrating the entire code block to PyQt6. Although I've already ran into a hiccup, which (of course this would happen) is directly related to the full screen enablement. Once I can import the module needed in PyQt6, that issue will be fixed and I can compile everything and upload the app.

**Comment by puppinoo** [comment]
Thats great to hear it.
Please let kme know if I can help somehow.
I can use your releases for testing and see if my issues are fixed.

**Comment by Meli10** [comment]
Working release is now up and ready for download!

**Comment by puppinoo** [comment]
Ill let you know ASAP.
Also the QT6 upgrade could improve things.
Thanks.

**Comment by Meli10** [comment]
Looking at the time of your message, I believe I have since re-uploaded a stable version of the release that might fix your problem. Also, I can implement DRM if need be as Qt6 supports DRM. Could you try refreshing the repo and re-downloading the exe using the releases page. I would refresh the repo by going to a different area of GitHub and then coming back to the repo (without back spacing or clicking the refresh button in browser) sometimes GitHub lags on refreshing newly pushed material.

Let me know if the more stable release .exe (I just uploaded) works for you. If not, I can explicitly add DRM support.

Currently, I’m running Fedora on a spare laptop but I have only tested the newly uploaded release on windows. I can boot Fedora and see if it runs for me there as well.

Thanks.

On Dec 7, 2023, at 1:45 AM, puppinoo ***@***.***> wrote:

﻿

Tried to make a quick test but it seems QT6 is not working form me. I suspect that Ubuntu 23.10 repo has QT6 compiled without proprietary codecs which are needed to enable DRM Widevine usage for proptected streams.
Can you tell me if you tested your browser on Ubuntu or any other distro?

Thanks.

**Comment by puppinoo** [comment]
Hi,
I cant use exe cause im in Ubuntu 23.10.
So I redownloaded the whole repo and launched the py file using
env QTWEBENGINE_DISABLE_SANDBOX=1 python3 main.py --no-sandbox
Bew still black screen when I tray to launch a stream.
I think it could be a issue my end cause QT6 on Ubuntu 23.10 repo could lack proprietary codecs but still not sure.

Ill retry this evening.

Regards

**Comment by Meli10** [comment]
I see what's happening here. Let me build an exe specifically for Linux. 

The issue here is the exe in the release currently was built using windows so it's utilizing windows files only. I need to create an exe for Linux users using Linux. The difference is os used for the build. By doing this, in the future, you won't need to clone the whole repo or need any dependencies. This will work out of the box as any other program. This will be done shortly

**Comment by Meli10** [comment]
I have just made an executable application tailored for Linux users. If you go to the Stratosphere release page and scroll to the bottom you will see 2 versions of the Rocket browser. Click the first one (Not the one labeled Rocket.exe) once downloaded, you should be able to launch it no problem. I have tested on my end (Using Fedora Linux) before uploading to GitHub.

If you have any more questions, please let me know.

Thanks again for the patience, I added a settings menu as well. Right now it only has a history option that you can view your history, clear it, or click on and navigate to websites displayed in history.

**Comment by puppinoo** [comment]
Hey,
Thanks a lot for your work.
I downloaded the binary and tried to use it but still gives me the same exact issue. everything works as soon as I try to launch a stream ojn paramountplus.com  . Can you tell me if you can open this stream file? I think it should implement the drm system I need for paramountplus.com

https://shaka-player-demo.appspot.com/demo/#audiolang=en;textlang=en;uilang=en;asset=https://storage.googleapis.com/shaka-demo-assets/sintel-widevine/dash.mpd;adTagUri=https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpod&cmsid=496&vid=short_onecue&correlator=;panel=HOME;build=uncompiled

If needed I can provide a temporary paramountplus.com account so you can test.
In the meantime I try to understand if my Ubuntu 23.10 has some issue.

Thanks.

**Comment by Meli10** [comment]
@puppinoo 
PyQt6's WebEngine is built on Chromium. So, in turn, using codecs like Widevine for DRM should be checked and looked for out of the box, **if you have it on your system**. Widevine is a good replacement/equivalent for flash player (since flash player is no longer a thing) for people looking to stream audio and video. That being said, there is a downside to using Widevine specifically.

1. Proprietary codecs owned by big companies like Google (They own Widevine) for example require special agreements and licenses when distributing their products to people in code or in an application.

2. There are open-source alternatives you may be interested in that should work with PyQt6 and don't require any special licenses or agreements. For streaming and for audio, Cisco has released their audio and video codecs as open source, according to PyQt if you have these on your system, you should be able to stream and listen to content that is DRM restricted.

3. Please consider doing the following:

The only thing I can do on my end set the WebEngine to enable plugins, Chromium should be doing the rest of the heavy lifting if it's available on your system.

Since you're running Ubuntu, you should open your terminal and type in the following commands 1 at a time:
`sudo apt update`
`sudo apt install gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly`

Once these have completed, (and I have pushed a newer release to enable plugins) I would start up the browser and see if you are able to watch your videos on Paramount plus.
